import type { Metadata } from "next";
import localFont from "next/font/local";
import { Montserrat, Niconne } from 'next/font/google';
import "./globals.css";

// Montserrat configuration
const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['100', '200', '400', '500', '600', '700', '800', '900'],
});

// Niconne configuration
const niconne = Niconne({
  subsets: ['latin'],
  weight: '400', // Niconne only comes in one weight
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} `}>
        {children}
      </body>
    </html>
  );
}
